[build.environment]
base=".nuxt"
publish=".nuxt/dist/client"
command="CI= npm run build"
[[redirects]]
  from = "/base/*"
  to = "http://143.198.103.113:8086/service/:splat"
  status = 200

[[redirects]]
  from = "/branch/*"
  to = "http://143.198.103.113:8086/main/:splat"
  status = 200
